-- Liste officielle des 45 villes HouseZone (recherche avancée / localisation).
-- Idempotent : n'ajoute que les villes manquantes, ne touche pas aux villes
-- déjà présentes ni aux quartiers/annonces existants.

insert into cities (name) values
  ('Ouagadougou'),
  ('Bobo-Dioulasso'),
  ('Koudougou'),
  ('Ouahigouya'),
  ('Banfora'),
  ('Kaya'),
  ('Pouytenga'),
  ('Fada N''Gourma'),
  ('Tenkodogo'),
  ('Houndé'),
  ('Dédougou'),
  ('Koupéla'),
  ('Réo'),
  ('Gourcy'),
  ('Léo'),
  ('Kongoussi'),
  ('Maina'),
  ('Yako'),
  ('Djibo'),
  ('Orodara'),
  ('Zorgho'),
  ('Manga'),
  ('Nouna'),
  ('Pô'),
  ('Tougan'),
  ('Diébougou'),
  ('Ziniaré'),
  ('Dori'),
  ('Garango'),
  ('Gaoua'),
  ('Solenzo'),
  ('Toma'),
  ('Titao'),
  ('Bogandé'),
  ('Boromo'),
  ('Boulsa'),
  ('Boussé'),
  ('Diapaga'),
  ('Gayéri'),
  ('Gorom-Gorom'),
  ('Pama'),
  ('Sapouy'),
  ('Batié'),
  ('Sebba'),
  ('Sindou')
on conflict (name) do nothing;
